#!/usr/bin/ruby
fname = ARGV[0]
dir = File.dirname(__FILE__)
bname = File.basename(fname).split(".")[0..-2].join(".")
system("ruby #{dir}/compiler.rb #{ARGV.join(" ")} 2>&1 >/tmp/#{bname}.s")
system("gcc -o /tmp/#{bname} /tmp/#{bname}.s")

puts "Compiled to /tmp/#{bname}"
