# # Very basic peephole optimizer
#
# This is *not* intended to be a general purpose peephole optimizer
# It's a quick and dirty hack to encapsulate optimizations that can
# be made quickly on the asm that is harder to fix in the higher level
# code generation. It is allowed to make assumptions about the generated
# code which may not hold for asm generated by anything else.
#
# This is i386 specific at the moment


class Peephole
  def initialize out
    @out = out
    @prev = []
  end

  def comment(str)
    #flush
    #@out.comment(str)
  end

  def export(label, type = nil)
    flush
    @out.export(label, type)
  end

  def label(l)
    flush
    @out.label(l)
  end

  def match(pat, test)
    return nil if pat.length != test.length
    res = []
    pat.each_with_index do |c,i|
      if c === test[i]
        res << test[i]
      else
        return nil
      end
    end
    return res
  end

  # Other patterns:
  # pushl %eax
  # movl ?, %eax
  # movl %eax, otherreg
  # popl %eax
  # ->
  # movl ?, reg

  # subl n, %esp
  # ... x ops not touching %esp
  # addl n, %esp
  # ->
  # ... x ops not touching %esp
  # *especially improving __int and __get_symbol init
  # Alt is handling the addl n, %esp/single instr not touching esp/subl n, %esp
  #
  # movl -n(%ebp), %eax
  # movl %eax, reg
  # popl %eax
  # movl %eax, (reg)
  # ->
  # movl -n(%ebp), reg
  # popl %eax
  # movl %eax, (reg)
  #
  #
  # subl x, %esp
  # op ?, reg
  # subl y, %esp
  # ->
  # subl x+y, %esp
  # op ?, reg
  #
  #
  # This *can't* be optimal:
  # movl n, %eax
  # cmpl %eax, %eax
  # setne %al
  # movzbl %al, %eax
  # testl %eax, %eax
  # je label
  #
  # Surely:
  # cmpl n, %eax
  # je label
  # must be enough?
  #
  #
  # movl n(%ebp), %esi
  # movl n(%ebp), %eax
  # must be a bug?
  #
  # movl -n(%ebp), %edx
  # pushl %edx
  # movl m(%ebp), %esi
  # popl %edi
  # movl %edi, o(%esi)
  # ->
  #movl m(%ebp), %esi
  #movl -n(%ebp), %edx
  #movl %edx, o(%esi)

  def peephole
    return if @prev.empty?

    args = @prev[-1]
    last = @prev[-2]

    if args[0] == :movb && args[1] == :eax
      @prev.pop
      @prev << [:movb, :al, args[2]]
      return
    end

    if fold_adjacent_add_sub(last, args)
      return
    end

    if fold_setcc_test_branch(args)
      return
    end

    # subl $0, reg  (inlined: peephole runs per instruction, so `match([:subl,0,Symbol], args)` allocated
    # a fresh 3-element pattern Array every emit)
    if args.length == 3 && args[0] == :subl && args[1] == 0 && args[2].is_a?(Symbol)
      @prev.pop
      return
    end

    if (args[0] == :movl || args[0] == :movb) && args[1] == args[2]
      @prev.pop
      return
    end

    # movl A, B ; movl B, A  ->  drop the second. After `movl A,B`, B holds A's value and A is unchanged,
    # so `movl B,A` is a no-op (reloads what A already has / stores back what B already holds). Covers both
    # compile_assign's store-then-reload (`movl %eax,mem; movl mem,%eax`) and load-then-store-back. At least
    # one of A/B is a register (x86 has no mem->mem movl), so this is always safe. `==` (not .class) so it
    # sees through Value-wrapped operands.
    if args[0] == :movl && last && last[0] == :movl &&
       last[1] == args[2] && last[2] == args[1] && last[1] != last[2]
      @prev.pop
      return
    end

    # Redundant reload of a never-written constant (nil/false/true) already in %eax. A `movl X, DEST` with
    # DEST != %eax cannot change %eax, so scanning back over such stores, if the last instruction that DID
    # write %eax loaded the same constant, this reload is redundant. nil/false/true are global objects set
    # once at init and never stored to, so their value can't have changed. Common in nil-init chains:
    # movl nil,%eax; movl %eax,L1; movl nil,%eax; movl %eax,L2; ...  (each reload after the first is dead).
    if args[0] == :movl && args[2] == :eax &&
       (args[1] == "nil" || args[1] == "false" || args[1] == "true")
      i = @prev.length - 2
      while i >= 0
        p = @prev[i]
        if p[0] == :movl && p[2] != :eax
          i -= 1                       # store to a non-eax dest: %eax unchanged, keep scanning
        else
          @prev.pop if p[0] == :movl && p[2] == :eax && p[1] == args[1]
          break                        # last %eax writer (or an op that may clobber %eax): stop
        end
      end
      return if @prev[-1] != args      # dropped it above
    end

    handle_simple_patterns(last, args)

    handle_mov_chain(args, last, @prev[-3])
  end

  def emit(*args)
    emit_row(args)
  end

  # Takes the already-built [op, *args] instruction row directly. The Emitter one-liner helpers build the
  # row inline (`@out.emit_row([:movl, s, d])`) and call this, avoiding Emitter#emit's throwaway *args Array
  # AND emit's own *args re-collect -- one Array per instruction instead of two, on both hosts.
  def emit_row(row)
    @prev << row
    l = @prev.length
    while l > 0
      peephole
      return if @prev.length >= l
      l = @prev.length
    end
  end

  def flush
    @prev.each do |row|
      @out.emit_row(row)
    end
    @prev = []
  end

  # setCC %al ; movzbl %al,%eax ; testl %eax,%eax ; jCC L
  # The comparison lowering (compile_comparison) materialises a 0/1 boolean in %eax, which is then tested to
  # branch. But setCC and movzbl leave the flags untouched, so the cmpl that fed the setCC is still live at
  # the testl -- the testl just re-derives the same ZF. Drop it and branch on those flags directly: a `je`
  # (taken when the boolean is 0, i.e. the setCC condition was FALSE) becomes the setCC's INVERSE branch; a
  # `jne` becomes the setCC's own branch. The setCC + movzbl are kept, so %eax still holds the boolean --
  # safe even where the fall-through path uses that value (e.g. `a && b`, which has no else arm).
  # Operand is the Symbol :al (compile_comparison), which excludes the float setCC path (string "%al").
  SETCC_INVERSE = {   # branch taken when the setCC condition is FALSE -- pairs with a `je` on the boolean
    :sete => :jne, :setne => :je, :setl => :jge, :setle => :jg,
    :setg => :jle, :setge => :jl, :seta => :jbe, :setae => :jb, :setb => :jae, :setbe => :ja,
  }.freeze
  SETCC_DIRECT = {    # branch taken when the setCC condition is TRUE -- pairs with a `jne` on the boolean
    :sete => :je, :setne => :jne, :setl => :jl, :setle => :jle,
    :setg => :jg, :setge => :jge, :seta => :ja, :setae => :jae, :setb => :jb, :setbe => :jbe,
  }.freeze

  def fold_setcc_test_branch(args)
    return false unless args[0] == :je || args[0] == :jne
    test = @prev[-2]
    mov  = @prev[-3]
    setcc = @prev[-4]
    return false unless test && mov && setcc
    return false unless test[0] == :testl && test[1] == :eax && test[2] == :eax
    return false unless mov[0] == :movzbl && mov[1] == :al && mov[2] == :eax
    return false unless setcc.length == 2 && setcc[1] == :al
    tbl = (args[0] == :je) ? SETCC_INVERSE : SETCC_DIRECT
    jcc = tbl[setcc[0]]
    return false unless jcc
    @prev.pop           # drop the branch
    @prev.pop           # drop the redundant testl
    @prev << [jcc, args[1]]
    true
  end

  # Helpers
  def fold_adjacent_add_sub(last, args)
    return false unless last
    return false unless last[1].is_a?(Integer) && args[1].is_a?(Integer)
    return false unless last[2] == args[2]

    # addl x, dest / subl y, dest
    if last[0] == :addl && args[0] == :subl
      @prev.pop
      @prev.pop
      if last[1] > args[1]
        @prev << [:addl, last[1] - args[1], args[2]]
      elsif last[1] < args[1]
        @prev << [:subl, args[1] - last[1], args[2]]
      end
      return true
    end

    # subl x, dest / subl y, dest
    if last[0] == :subl && args[0] == :subl
      @prev.pop
      @prev.pop
      @prev << [:subl, args[1] + last[1], args[2]]
      return true
    end

    false
  end

  def handle_simple_patterns(last, args)
    return false unless last

    return true if handle_push_pop_patterns(last, args)

    false
  end

  MINUS4_EBP = "-4(%ebp)".freeze

  def handle_push_pop_patterns(last, args)
    # inlined equality (the two Array literals + the string literal allocated every emit)
    if last.length == 2 && last[0] == :pushl && last[1] == :ebx &&
       args.length == 3 && args[0] == :movl && args[1] == MINUS4_EBP && args[2] == :eax
      @prev.pop
      @prev << [:movl, :ebx, :eax]
      return true
    end

    if last[0] == :pushl && args[0] == :popl && last[1] == args[1]
      @prev.pop
      @prev.pop
      return true
    end

    # pushl X ; popl Y  (X != Y)  ->  movl X, Y
    # A value transfer routed through the stack: pushl reads X, popl writes it to Y, %esp nets to zero. A
    # direct move is equivalent and cheaper (one instruction, and no memory traffic). Guards: one operand
    # must be a register (Symbol) so we never form an illegal mem->mem move, and neither may be
    # %esp-relative -- for those the push/pop's own %esp adjustment changes what the operand addresses, so
    # the transfer is NOT a plain move. Emitted e.g. by register save/restore around a temporary.
    if last[0] == :pushl && args[0] == :popl && last[1] != args[1]
      x = last[1]
      y = args[1]
      if (x.is_a?(Symbol) || y.is_a?(Symbol)) && !esp_operand?(x) && !esp_operand?(y)
        @prev.pop
        @prev.pop
        @prev << [:movl, x, y]
        return true
      end
    end

    false
  end

  # True if an operand reads/writes memory relative to %esp (or is %esp itself), whose value shifts under a
  # push/pop -- such an operand can't participate in the pushl/popl -> movl fold.
  def esp_operand?(o)
    return true if o == :esp
    o.is_a?(String) && o.include?("esp")
  end

  # True if an operand is an IMMEDIATE value: a numeric literal (stored as Integer, rendered "$N") or an
  # address literal (stored as a "$label" String). x86 allows an immediate source in a movl to ANY
  # destination, including memory -- unlike a memory source (a bare-label/`-N(%ebp)` String), which can't
  # target memory. So an immediate src lets the mov-chain fold apply even when the dest is memory. A String
  # WITHOUT a leading "$" (e.g. "nil", "Class", "-4(%ebp)") is a memory reference, NOT an immediate.
  def immediate_operand?(o)
    return true if o.is_a?(Integer)
    o.is_a?(String) && o.start_with?("$")
  end

  def handle_mov_chain(args, last, last2)
    return unless last2
    return unless last2[0] == :movl && last2[2] == :eax

    # movl src, %eax; movl %eax, dest; <insn overwriting %eax> -> movl src, dest; <insn>
    # The third instruction overwrites %eax without reading it, so the value the first put there is dead:
    # the round-trip through %eax can be dropped as long as `movl src, dest` is itself a legal mov -- i.e.
    # src OR dest is a register (x86 forbids only memory->memory; here a register operand is a Symbol,
    # memory/immediate/label a String). Originally only a register SRC was folded; a register DEST (e.g.
    # movl -4(%ebp),%eax; movl %eax,%edx; movl ?,%eax  ->  movl -4(%ebp),%edx; movl ?,%eax) is equally safe
    # and far more common. The %eax killer is either a `movl ???,%eax` OR a `popl %eax` -- the latter is the
    # dominant form (`movl Class,%eax; movl %eax,%edx; popl %eax; movl %eax,(%edx)`, ~3.6k in a self-compile:
    # a value is loaded, copied to an address register, then %eax is reused for the popped store value).
    eax_killed = (args[0] == :movl && args[2] == :eax) ||
                 (args[0] == :popl && args[1] == :eax)
    if last && last[0] == :movl && last[1] == :eax && eax_killed
      src = last2[1]
      dest = last[2]
      # Legal as long as it isn't memory->memory. A register src/dest (Symbol) covers most cases; ALSO
      # allow an immediate src (`movl $IMM,%eax; movl %eax,mem; <kill>` -> `movl $IMM,mem`), which is legal
      # to a memory dest and was previously rejected because "$..."/Integer looked like a non-register.
      if src.is_a?(Symbol) || dest.is_a?(Symbol) || immediate_operand?(src)
        @prev.pop
        @prev.pop
        @prev.pop
        @prev << [:movl, src, dest]
        @prev << args
        return
      end
    end

    # movl Int|Reg, %eax; subl %eax, reg; movl ???, %eax -> subl val, reg; movl ???, %eax
    if last2[1].class == Symbol || last2[1].is_a?(Integer)
      val = last2[1]
      if last && last[0] == :subl && last[1] == :eax && last[2].class == Symbol
        reg = last[2]
        if args[0] == :movl && args[1] != :eax && args[2] == :eax
          @prev.pop
          @prev.pop
          @prev.pop
          @prev << [:subl, val, reg]
          @prev << args
          return
        end
      end
    end
  end

end
