
#
# We re-open class here, after Hash and Symbol has ben initialized, to add the 
# method -> vtable offset mapping.
#

class Class
  @method_to_voff = {}

  # FIXME
  def self.new(super=nil)
    self
  end
  
  def self.method_to_voff
    @method_to_voff
  end

  def method_missing sym, *args
      %s(if sym (printf "WARNING:    Method: '%s'\n" (callm (callm sym to_s) __get_raw)))
      %s(printf "WARNING:    symbol address = %p\n" sym)
      %s(printf "WARNING:    class '%s'\n" (callm (callm self name) __get_raw))
      %s(call exit 1)
  end

  # This is called by __send__
  def __send_for_obj__ obj,sym,*args
    sym  = sym.to_sym
    voff = Class.method_to_voff[sym]
    if !voff
      # FIXME: This needs to change once we handle "define_method"
      return obj.method_missing(sym, *args)
    else
      # We can't inline this in the call, as our updated callm
      # doesn't allow method/function calls in the method slot
      # for simplicity, for now anyway.
      %s(assign raw (callm voff __get_raw))
      %s(callm obj (index self raw) ((splat args)))
    end
  end

#  def ===(o)
#    o.is_a?(self)
#  end

  # FIXME: Belongs in Kernel
end

%s(sexp
(defun __printerr (format a1 a2 a3) (do
   (printf format a1 a2 a3)
   (div 1 0)
))

(defun __minarg (name minargs actual)
  (let (__argbuf __argmsg __argexc) (do
    (assign __argbuf (__alloc_leaf 200))
    (snprintf __argbuf 200 "wrong number of arguments (given %d, expected %d+)"
      (sub actual 2) minargs)
    (assign __argmsg (__get_string __argbuf))
    (assign __argexc (callm ArgumentError new __argmsg))
    (callm $__exception_runtime raise __argexc)
  ))
)


(defun __maxarg (name maxargs actual)
  (let (__argbuf __argmsg __argexc) (do
    (assign __argbuf (__alloc_leaf 200))
    (snprintf __argbuf 200 "wrong number of arguments (given %d, expected 0..%d)"
      (sub actual 2) maxargs)
    (assign __argmsg (__get_string __argbuf))
    (assign __argexc (callm ArgumentError new __argmsg))
    (callm $__exception_runtime raise __argexc)
  ))
)

 (defun __eqarg (name eqargs actual)
  (let (__argbuf __argmsg __argexc) (do
    (assign __argbuf (__alloc_leaf 200))
    (snprintf __argbuf 200 "wrong number of arguments (given %d, expected %d)"
      (sub actual 2) eqargs)
    (assign __argmsg (__get_string __argbuf))
    (assign __argexc (callm ArgumentError new __argmsg))
    (callm $__exception_runtime raise __argexc)
  ))
)

)

#
# Populate the Class.method_to_voff hash based on the __vtable_names
# table that gets generated by the compiler.
#
%s(let (i max ptr)
   (assign i 0)
   (assign max __vtable_size)
   (assign h (callm Class method_to_voff))
   (while (lt i max) 
      (do
        (assign ptr (index __vtable_names i))
        (if (ne ptr 0)
          (callm h []= ((__get_symbol ptr) (__int i)))
        )
        (assign i (add i 1))
      )
    )
  )
