
#
# We re-open class here, after Hash and Symbol has ben initialized, to add the 
# method -> vtable offset mapping.
#

class Class
  # FIXME
  def self.new(super=nil)
    self
  end

  # Lazily initialise the method-name -> vtable-offset map. This is a class-object ivar (self is the
  # Class object), which is stored per-class in a global; initialising it here in the reader keeps every
  # access on that single global. (A bare `@method_to_voff = {}` in the class body instead resolves to a
  # slot, which would not be the same storage the eigenclass reader/writer uses.)
  def self.method_to_voff
    @method_to_voff ||= {}
    @method_to_voff
  end

  # Case-equality for classes: `Klass === obj` iff obj.is_a?(Klass). Needed because the
  # generic Object#=== is `==`, which is never true for a class vs an instance.
  def ===(other)
    other.is_a?(self)
  end

  # This is called by __send__. `blk` is the block to forward (nil when none) -- passed as the 4th element
  # of the callm s-expr, which compile_callm threads in as the callee's __closure__, so send/to_enum work.
  def __send_for_obj__ obj,sym,blk,*args
    sym  = sym.to_sym
    voff = Class.method_to_voff[sym]
    if !voff
      # No compile-time vtable slot (name never statically def'd). Route through
      # __dispatch_missing__ (runtime define_method registry, then method_missing) and
      # forward the block (the old direct method_missing call dropped it).
      return obj.__dispatch_missing__(sym, *args, &blk)
    else
      # We can't inline this in the call, as our updated callm
      # doesn't allow method/function calls in the method slot
      # for simplicity, for now anyway.
      %s(assign raw (callm voff __get_raw))
      # With no block, use the block-less callm so the closure slot gets raw 0 (the no-block convention);
      # passing a tagged nil there would make the callee mis-read it as a present closure.
      if blk
        %s(callm obj (index self raw) ((splat args)) blk)
      else
        %s(callm obj (index self raw) ((splat args)))
      end
    end
  end

#  def ===(o)
#    o.is_a?(self)
#  end

  # FIXME: Belongs in Kernel
end

%s(sexp
(defun __printerr (format a1 a2 a3) (do
   (printf format a1 a2 a3)
   (div 1 0)
))

(defun __minarg (name minargs actual)
  (let (__argbuf __argmsg __argexc) (do
    (assign __argbuf (__alloc_leaf 200))
    (snprintf __argbuf 200 "wrong number of arguments (given %d, expected %d+)"
      (sub actual 2) minargs)
    (assign __argmsg (__get_string __argbuf))
    (assign __argexc (callm ArgumentError new __argmsg))
    (callm $__exception_runtime raise __argexc)
  ))
)


(defun __maxarg (name maxargs actual)
  (let (__argbuf __argmsg __argexc) (do
    (assign __argbuf (__alloc_leaf 200))
    (snprintf __argbuf 200 "wrong number of arguments (given %d, expected 0..%d)"
      (sub actual 2) maxargs)
    (assign __argmsg (__get_string __argbuf))
    (assign __argexc (callm ArgumentError new __argmsg))
    (callm $__exception_runtime raise __argexc)
  ))
)

 (defun __eqarg (name eqargs actual)
  (let (__argbuf __argmsg __argexc) (do
    (assign __argbuf (__alloc_leaf 200))
    (snprintf __argbuf 200 "wrong number of arguments (given %d, expected %d)"
      (sub actual 2) eqargs)
    (assign __argmsg (__get_string __argbuf))
    (assign __argexc (callm ArgumentError new __argmsg))
    (callm $__exception_runtime raise __argexc)
  ))
)

)

#
# Populate the Class.method_to_voff hash based on the __vtable_names
# table that gets generated by the compiler.
#
%s(let (i max ptr)
   (assign i 0)
   (assign max __vtable_size)
   (assign h (callm Class method_to_voff))
   (while (lt i max) 
      (do
        (assign ptr (index __vtable_names i))
        (if (ne ptr 0)
          (callm h []= ((__get_symbol ptr) (__int i)))
        )
        (assign i (add i 1))
      )
    )
  )
